apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-currency
  labels:
    app: muffin-currency
spec:
  type: {{ .Values.service.type }}
  selector:
    app: muffin-currency
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
