apiVersion: v1
kind: ConfigMap
metadata:
  name: muffin-wallet
data:
  application.yaml: |
    server:
      port: {{ .Values.config.serverPort }}
    spring:
      datasource:
        url: {{ .Values.config.datasourceUrl | quote }}
        username: {{ .Values.config.datasourceUsername | quote }}
    currency:
      service:
        url: {{ .Values.config.currencyServiceUrl | quote }}
    management:
      endpoints:
        web:
          exposure:
            include: health, info
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
