apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: muffin-ingress
  namespace: muffin
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - muffin.local
      secretName: muffin-tls
  rules:
    - host: muffin.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: muffin-svc
                port:
                  number: 80
